
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class D_DeviceEnvironmentt
{

    public long id { get; set; }

    public string mac { get; set; }

    public string hum { get; set; }

    public string tempc { get; set; }

    public Nullable<int> status { get; set; }

    public Nullable<System.DateTime> creattime { get; set; }

    public Nullable<System.DateTime> StartDateTime { get; set; }

    public Nullable<System.DateTime> EndDateTime { get; set; }

}

}
