
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class D_DeviceGroup
{

    public long ID { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public Nullable<long> ParentGroupID { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<long> CreateUserID { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public Nullable<long> UpdateUserID { get; set; }

    public Nullable<long> OrgID { get; set; }

    public string Image { get; set; }

}

}
