
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class D_IoTHubConfiguration
{

    public long ID { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int Type { get; set; }

    public string Url { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public System.DateTime CreateTime { get; set; }

    public Nullable<long> CreateUserID { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public Nullable<long> UpdateUserID { get; set; }

    public long OrgID { get; set; }

    public string Remark { get; set; }

}

}
