
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class D_MedicineListInfo
{

    public long Id { get; set; }

    public string mac { get; set; }

    public string CabintId { get; set; }

    public Nullable<int> MedicinePrice { get; set; }

    public Nullable<long> MedicineId { get; set; }

    public string MedicineName { get; set; }

    public Nullable<int> Count { get; set; }

    public string manuName { get; set; }

    public string spec { get; set; }

    public Nullable<System.DateTime> CreatTime { get; set; }

    public Nullable<System.DateTime> StartDateTime { get; set; }

    public Nullable<System.DateTime> EndDateTime { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string tableId { get; set; }

}

}
