
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class D_MedicineListInfoModel
{

    public long id { get; set; }

    public string mac { get; set; }

    public string goodName { get; set; }

    public Nullable<long> code { get; set; }

    public string manuName { get; set; }

    public string img { get; set; }

    public string spec { get; set; }

    public string price { get; set; }

    public Nullable<int> count { get; set; }

    public Nullable<System.DateTime> creattime { get; set; }

    public Nullable<System.DateTime> StartDateTime { get; set; }

    public Nullable<System.DateTime> EndDateTime { get; set; }

}

}
