
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class M_Medicine
{

    public int id { get; set; }

    public string product_pzwh { get; set; }

    public string product_format { get; set; }

    public string product_name { get; set; }

    public string product_manufacturer { get; set; }

    public string product_barcode { get; set; }

    public string product_form { get; set; }

    public string product_wholesale_price { get; set; }

    public string product_retail_price { get; set; }

    public System.DateTime create_time { get; set; }

    public string img { get; set; }

}

}
