

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MonitoringEntities : DbContext
{
    public MonitoringEntities()
        : base("name=MonitoringEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<A_AlarmHistory> A_AlarmHistory { get; set; }

    public virtual DbSet<A_AlarmStrategy> A_AlarmStrategy { get; set; }

    public virtual DbSet<D_AlarmDoorPolicies> D_AlarmDoorPolicies { get; set; }

    public virtual DbSet<D_AlarmStrategy> D_AlarmStrategy { get; set; }

    public virtual DbSet<D_AlertPolicies> D_AlertPolicies { get; set; }

    public virtual DbSet<D_DataConnectConfiguration> D_DataConnectConfiguration { get; set; }

    public virtual DbSet<D_DeviceBuilding> D_DeviceBuilding { get; set; }

    public virtual DbSet<D_DeviceEnvironmentt> D_DeviceEnvironmentt { get; set; }

    public virtual DbSet<D_DeviceGroup> D_DeviceGroup { get; set; }

    public virtual DbSet<D_DeviceModel> D_DeviceModel { get; set; }

    public virtual DbSet<D_DeviceModelItem> D_DeviceModelItem { get; set; }

    public virtual DbSet<D_Devices> D_Devices { get; set; }

    public virtual DbSet<D_DevicesItem> D_DevicesItem { get; set; }

    public virtual DbSet<D_IoTHubConfiguration> D_IoTHubConfiguration { get; set; }

    public virtual DbSet<D_MedicineInfo> D_MedicineInfo { get; set; }

    public virtual DbSet<D_MedicineListInfo> D_MedicineListInfo { get; set; }

    public virtual DbSet<D_MedicineListInfoModel> D_MedicineListInfoModel { get; set; }

    public virtual DbSet<M_Medicine> M_Medicine { get; set; }

    public virtual DbSet<U_Enumerations> U_Enumerations { get; set; }

    public virtual DbSet<U_HomeConfiguration> U_HomeConfiguration { get; set; }

    public virtual DbSet<U_Message> U_Message { get; set; }

    public virtual DbSet<U_Organization> U_Organization { get; set; }

    public virtual DbSet<U_PhoneCode> U_PhoneCode { get; set; }

    public virtual DbSet<U_StaticParam> U_StaticParam { get; set; }

    public virtual DbSet<U_Token> U_Token { get; set; }

    public virtual DbSet<U_User> U_User { get; set; }

    public virtual DbSet<U_UserLoginErrorInfo> U_UserLoginErrorInfo { get; set; }

    public virtual DbSet<U_UserMessageRel> U_UserMessageRel { get; set; }

    public virtual DbSet<U_UserOrganizationRel> U_UserOrganizationRel { get; set; }

}

}

