
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace DeviceMonitoringDAL
{

using System;
    using System.Collections.Generic;
    
public partial class U_HomeConfiguration
{

    public long ID { get; set; }

    public Nullable<int> DashBoardType { get; set; }

    public Nullable<long> DeviceID { get; set; }

    public Nullable<long> DeviceItemID { get; set; }

    public string ChartName { get; set; }

    public Nullable<int> ChartType { get; set; }

    public string ChartConfig { get; set; }

    public string DashBoardData { get; set; }

    public string Remark { get; set; }

    public Nullable<int> SortID { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<long> CreateUserID { get; set; }

    public Nullable<long> OrgID { get; set; }

    public Nullable<long> GroupID { get; set; }

}

}
