
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UserDAL
{

using System;
    using System.Collections.Generic;
    
public partial class U_Organization
{

    public long ID { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string Area { get; set; }

    public string Town { get; set; }

    public string Street { get; set; }

    public string AddressDetail { get; set; }

    public string LogoUrl { get; set; }

    public string ContactName { get; set; }

    public string ContactPhone { get; set; }

    public string FixedPhone { get; set; }

    public string Fax { get; set; }

    public string ZipCode { get; set; }

    public string Email { get; set; }

    public string State { get; set; }

    public string TradeLevel1 { get; set; }

    public string TradeLevel2 { get; set; }

    public string LocationAddress { get; set; }

    public Nullable<System.DateTime> RegistrationTime { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<long> CreateUserId { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public Nullable<long> UpdateUserId { get; set; }

    public string Site { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> ValidFrom { get; set; }

    public Nullable<System.DateTime> ValidTo { get; set; }

}

}
