
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UserDAL
{

using System;
    using System.Collections.Generic;
    
public partial class U_StaticParam
{

    public long ID { get; set; }

    public string StaticName { get; set; }

    public string StaticKey { get; set; }

    public string StaticValue { get; set; }

    public Nullable<long> ParentID { get; set; }

    public Nullable<System.DateTime> StartDateTime { get; set; }

    public Nullable<System.DateTime> EndDateTime { get; set; }

    public Nullable<long> SortID { get; set; }

}

}
