
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UserDAL
{

using System;
    using System.Collections.Generic;
    
public partial class U_User
{

    public long ID { get; set; }

    public string AccountId { get; set; }

    public string Name { get; set; }

    public string PassWord { get; set; }

    public string Type { get; set; }

    public string Email { get; set; }

    public string ContactPhone { get; set; }

    public Nullable<int> IsAdmin { get; set; }

    public Nullable<int> IsManageAdmin { get; set; }

    public string HeadImgUrl { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string Status { get; set; }

    public string LockState { get; set; }

    public Nullable<System.DateTime> LastLoginDate { get; set; }

    public Nullable<System.DateTime> UpdateTime { get; set; }

    public Nullable<System.DateTime> ValidFrom { get; set; }

    public Nullable<System.DateTime> ValidTo { get; set; }

}

}
