

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace UserDAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class UserEntities : DbContext
{
    public UserEntities()
        : base("name=UserEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<U_Enumerations> U_Enumerations { get; set; }

    public virtual DbSet<U_HomeConfiguration> U_HomeConfiguration { get; set; }

    public virtual DbSet<U_Message> U_Message { get; set; }

    public virtual DbSet<U_Organization> U_Organization { get; set; }

    public virtual DbSet<U_PhoneCode> U_PhoneCode { get; set; }

    public virtual DbSet<U_StaticParam> U_StaticParam { get; set; }

    public virtual DbSet<U_Token> U_Token { get; set; }

    public virtual DbSet<U_User> U_User { get; set; }

    public virtual DbSet<U_UserLoginErrorInfo> U_UserLoginErrorInfo { get; set; }

    public virtual DbSet<U_UserMessageRel> U_UserMessageRel { get; set; }

    public virtual DbSet<U_UserOrganizationRel> U_UserOrganizationRel { get; set; }

}

}

