//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerSoft.IndApp.AlertPoliciesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AlarmStrategy
    {
        public long ID { get; set; }
        public string StrategyName { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public Nullable<long> DataConnectID { get; set; }
        public string TagMap { get; set; }
        public Nullable<long> DeviceItemId { get; set; }
        public string Compare { get; set; }
        public string Threshold { get; set; }
        public string Remark { get; set; }
        public Nullable<long> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> Interval { get; set; }
        public Nullable<bool> Active { get; set; }
        public long OrgID { get; set; }
    }
}
