//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerSoft.IndApp.AlertPoliciesDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlertPoliciesEntities : DbContext
    {
        public AlertPoliciesEntities()
            : base("name=AlertPoliciesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_AlarmHistory> A_AlarmHistory { get; set; }
        public virtual DbSet<A_AlarmStrategy> A_AlarmStrategy { get; set; }
    }
}
